---
- name: Install wifi-bluetooth pkgs
  pacman:
    name:
      - bluez
      - bluez-libs
      - bluez-utils
      - dialog
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - wpa_actiond
      - wpa_supplicant
    update_cache: yes
    state: present

- name: Enable bluetooth
  service: name=bluetooth enabled=yes
