---
- name: Install wifi-bluetooth pkgs
  pacman:
    name:
      - bluez
      - bluez-libs
      - bluez-utils
      - dialog
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - wpa_actiond
      - wpa_supplicant
    update_cache: yes
    state: present
  
- name: enable bluetooth
  service: name=bluetooth enabled=yes

#- name: enable netctl-auto
#  service: name=netctl-auto@{{ wifi.interface }}.service enabled=yes
#
#- name: Copy wifi connections
#  template:
#    src: "{{ item }}"
#    dest: /etc/netctl/{{ wifi.interface }}-{{ item }}
#  with_items:
#    - IONIS
#    - evolukek
#    - myHTTPd_secure
