- name: Install wifi-bluetooth pkgs
  pacman:
    name:
      - bluez
      - bluez-utils
      - wpa_supplicant
      - dialog
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - bluez-libs
      - wpa_actiond
    update_cache: yes
    state: present
  
- name: enable bluetooth
  service: name=bluetooth enabled=yes

- name: enable netctl-auto
  service: name=netctl-auto@{{ wifi.interface }}.service enabled=yes
