---
- name: Install xfce4-notifyd
  pacman:
    state: present
    name:
      - xfce4-notifyd

- name: Config xfce4-notifyd
  lineinfile:
    dest: "{{ user.home }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml"
    regexp: "do-slideout"
    state: present
    line: "  <property name=\"do-slideout\" type=\"bool\" value=\"true\"/>"

