---
- name: Make directory for user SSH key
  file:
    path: "{{ user.home }}/.ssh"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: SSH Config
  copy:
    dest: "{{ user.home }}/.ssh/config"
    src: sshconfig
    owner: "{{ user.name }}"
