syntax on
set backspace=eol,indent,start
set number
set laststatus=2
set statusline=%f\ %l\|%c\ %m%=%p%%\ (%Y%R)
set tabstop=8
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab
set autoindent
set cinoptions=(0,u0,U0,t0,g0,N-s
set switchbuf=usetab,newtab,useopen
let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
