---
- name: Install YubiKey Personalization GUI
  pacman: name=yubikey-personalization-gui state=present

- name: Install smartcard libs/tools
  pacman:
    state: present
    name:
      - pcsclite
      - libusb-compat
      - ccid
