---
- name: Install LightDM
  pacman:
    state: present
    name:
      - lightdm
      - lightdm-gtk-greeter

- name: Enable LightDM
  service: name=lightdm.service enabled=yes
  when: no_systemd is not defined or not no_systemd

- name: Create background dir
  file: path=/usr/share/backgrounds state=directory

- name: Push LightDM greeter background
  copy: src=background.png dest=/usr/share/backgrounds/background.png

- name: Specify LightDM greeter background
  lineinfile: dest=/etc/lightdm/lightdm-gtk-greeter.conf
              regexp="^background="
              state=present
              line="background=/usr/share/backgrounds/background.png"

- name: Hide user images
  lineinfile: dest=/etc/lightdm/lightdm-gtk-greeter.conf
              regexp="^hide-user-image="
              state=present
              line="hide-user-image=true"

- name: Force LightDM greeter theme
  lineinfile: dest=/usr/share/xgreeters/lightdm-gtk-greeter.desktop
              regexp="^Exec="
              state=present
              line="Exec=env GTK_THEME=Adwaita:dark lightdm-gtk-greeter"

- name: Install xinit-xsession
  aur:
    use: trizen
    name:
      - xinit-xsession
  become: yes
  become_user: aurbuilder
