---
- name: Install Docker
  package:
    name:
      - docker
      - docker-compose

- name: Install docker tools
  aur:
    name:
      - lazydocker-git
      - ctop-bin
    use: trizen
  become_user: aurbuilder
  become: yes

- name: Install nvidia-docker
  aur:
    name: nvidia-docker
    use: trizen
  become_user: aurbuilder
  become: yes
  when: gpu is defined and gpu == 'nvidia'

- name: Add user to group docker
  user:
    name: '{{ user.name }}'
    groups: docker
    append: yes
