---
- name: Install download tools
  pacman:
    name:
      - deluge
      - transmission-gtk

- name: Install windscribe-cli and webtorrent-desktop
  aur:
    use: trizen
    name:
      - webtorrent-desktop-bin
      - windscribe-cli
  become: yes
  become_user: aurbuilder
