---
- name: Install download tools
  pacman:
    name:
      - transmission-gtk
      - deluge

- name: Install windscribe-cli and webtorrent-desktop
  aur:
    use: trizen
    name:
      - windscribe-cli
      - webtorrent-desktop-bin
  become: yes
  become_user: aurbuilder
