---

- hosts: all
  gather_facts: no
  roles:
    - bootstrap

- hosts: all
  tasks:
    - group_by: key=os_{{ ansible_distribution }}

- hosts: all
  roles:
    - { role: common, tags: ['common'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: users, tags: ['users'] }
