---

- name: Install the base packages
  command: pacstrap -c "{{ install.mountpoint }}"
    ansible
    base
    base-devel
    linux
    lvm2
    openssh
    vim

- name: Generate fstab
  command: genfstab -U "{{ install.mountpoint }}"
  register: fstab

- name: Write fstab
  copy:
    content: "{{ fstab.stdout }}"
    dest: "{{ install.mountpoint }}/etc/fstab"

- name: Link localtime
  file:
    state: link
    follow: no
    path: "{{ install.mountpoint }}/etc/localtime"
    src: "/usr/share/zoneinfo/{{ timezone.region }}/{{ timezone.city }}"

- name: Set the Hardware Clock from the System Clock
  command: arch-chroot "{{ install.mountpoint }}" hwclock --systohc

- name: Locale generation configuration
  lineinfile:
    path: "{{ install.mountpoint }}/etc/locale.gen"
    line: "en_US.UTF-8 UTF-8"

- name: Locale generation
  command: arch-chroot "{{ install.mountpoint }}" locale-gen

- name: Locale configuration
  copy:
    dest: "{{ install.mountpoint }}/etc/locale.conf"
    content: "LANG=en_US.UTF-8"

- name: Set hostname
  copy:
    dest: "{{ install.mountpoint }}/etc/hostname"
    content: "{{ hostname }}"

- name: Generate pass hash
  delegate_to: localhost
  command: "python3 -c
    'import crypt; \
    print(crypt.crypt(\"{{ install.password }}\", \
    crypt.mksalt(crypt.METHOD_SHA512)))'"
  register: hash

- name: Change root password
  command: arch-chroot "{{ install.mountpoint }}"
    usermod --password "{{ hash.stdout }}" root

- name: Install systemd-boot
  command: arch-chroot "{{ install.mountpoint }}" bootctl --path=/boot install

- name: Get UUID of LUKS partition
  command: blkid /dev/disk/by-partlabel/LUKS -s UUID -o value
  register: luks_uuid

- name: Copy boot entry
  template:
    src: archlinux.conf
    dest: "{{ install.mountpoint }}/boot/loader/entries/archlinux.conf"
  when: item.item.lv == install.lv_root
  with_items: "{{ mapped_names.results }}"

- name: Configure hooks
  lineinfile:
    regexp: "^HOOKS="
    line: "HOOKS=(\
      base \
      udev \
      autodetect \
      keyboard \
      keymap \
      modconf \
      block \
      encrypt \
      lvm2 \
      filesystems \
      keyboard \
      fsck)"
    path: "{{ install.mountpoint }}/etc/mkinitcpio.conf"

- name: Configure hooks (Regenerate initramfs)
  command: arch-chroot "{{ install.mountpoint }}" mkinitcpio -p linux

- name: Install ucode
  command: pacstrap "{{ install.mountpoint }}" intel-ucode
  when: cpu is defined and cpu == "intel"

- name: Add ucode initrd
  lineinfile:
    path: "{{ install.mountpoint }}/boot/loader/entries/archlinux.conf"
    line: "initrd /intel-ucode.img"
    insertbefore: "initrd /initramfs-linux.img"
  when: cpu is defined and cpu == "intel"
