---

- name: Allow root login
  lineinfile:
    path: "{{ install.mountpoint }}/etc/ssh/sshd_config"
    line: "PermitRootLogin yes"
    regexp: "^PermitRootLogin "

- name: Configure ssh port
  lineinfile:
    path: "{{ install.mountpoint }}/etc/ssh/sshd_config"
    line: "Port 2222"
    regexp: "^Port "

- name: Genrerate tmp key and start sshd
  command: arch-chroot "{{ install.mountpoint }}" sh -c "ssh-keygen -b 521 -t ecdsa -f /tmp/id_ecdsa -P '' && /usr/bin/sshd -h /tmp/id_ecdsa && sleep infinity"
