---

- name: Update the system clock
  command: timedatectl set-ntp true

- name: Select the mirrors
  lineinfile:
    path: /etc/pacman.d/mirrorlist
    line: 'Server  =  http://archlinux.de-labrusse.fr/$repo/os/$arch'
    insertbefore: BOF

- name: Update archlinux-keyring
  pacman:
    update_cache: yes
    state: present
    name:
      - archlinux-keyring
  when: false
